### ISSUE TITLE
Missing guid from .meta file

### ISSUE THREAD

**Issue by asbjornu** [firebase-unity/firebase-app#1]
After adding `"com.google.firebase.app": "https://github.com/firebase-unity/firebase-app.git#11.6.0",` to `manifest.json` and performing a build, Unity complains about the following:

> The `.meta` file `Packages/com.google.firebase.app/Firebase/Plugins/x86_64/FirebaseCppApp-11_6_0.bundle.meta` does not have a valid GUID and its corresponding Asset file will be ignored. If this file is not malformed, please add a GUID, or delete the .meta file and it will be recreated correctly

I can't find the file `Packages/com.google.firebase.app/Firebase/Plugins/x86_64/FirebaseCppApp-11_6_0.bundle.meta`, but at the path `./Library/PackageCache/com.google.firebase.app@7ce22fc8ee/Firebase/Plugins/x86_64/FirebaseCppApp-11_6_0.bundle` I find a file with the following contents:

```
version https://git-lfs.github.com/spec/v1
oid sha256:b504c59beef4f1ce429c97df41cfa70fa8befd2429dcfcd422b9282db178843b
size 162105481
```

And it is indeed missing a `guid` property.

**Comment by yenmoc** [comment]
This is probably because the bandwidth of LFS storage is limited at the time you fetch the package. Because I received an email saying that the bandwidth was exceeded around that time and then I extended the bandwidth. You can let Unity Package Manager reload the package and test it again
